
version: '3'
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: stepan2204/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
    depends_on:
      - db
  gateway:
    image: stepan2204/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
    depends_on:
      - backend
    ports:
      - 8002:80

