# Generated by Django 3.2.3 on 2024-10-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagecapacity',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
