# Generated by Django 3.2.3 on 2024-10-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_alter_storagecapacity_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcapacity',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities_organisatiom', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='storagecapacity',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities_storage', to='organisations.storage'),
        ),
    ]
