# Generated by Django 3.2.3 on 2024-10-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20241026_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationcapacity',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities_organisation', to='organisations.organisation'),
        ),
    ]
