# Generated by Django 3.2.3 on 2024-11-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_alter_organisationcapacity_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationstorage',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages_organisation', to='organisations.organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
